import type { Tool, Utility, Workflow } from './types';

export const AI_TOOLS_DATA: Tool[] = [
  {
    id: '1',
    slug: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    summary: 'Google\'s fast and versatile multimodal model, great for a wide range of tasks.',
    websiteUrl: 'https://deepmind.google/technologies/gemini/',
    logoUrl: 'https://picsum.photos/seed/gemini/100',
    pricingModel: 'Usage-based',
    freeTier: true,
    rating: 4.8,
    verdict: 'The best all-around model for speed and capability. Excellent for creative text generation and multimodal inputs.',
    pros: ['Extremely fast', 'High context window', 'Strong multimodal capabilities'],
    cons: ['Can be less nuanced than larger models', 'Still in preview for some features'],
    bestFor: 'Chatbots, content summarization, and quick analysis.',
    quickstart: ['Get an API key from Google AI Studio.', 'Use the @google/genai SDK.', 'Call `ai.models.generateContent` with your prompt.'],
    categories: ['Language Models', 'Multimodal'],
    tags: ['Google', 'LLM', 'Fast', 'API'],
    youtubeReviewId: 'KkEMg-a_o5k',
  },
  {
    id: '2',
    slug: 'claude-3-opus',
    name: 'Claude 3 Opus',
    summary: 'Anthropic\'s most powerful model, excelling at complex reasoning and long-context tasks.',
    websiteUrl: 'https://www.anthropic.com/news/claude-3-family',
    logoUrl: 'https://picsum.photos/seed/claude/100',
    pricingModel: 'Usage-based',
    freeTier: false,
    rating: 4.9,
    verdict: 'The top choice for tasks requiring deep reasoning, analysis of large documents, and enterprise-level reliability.',
    pros: ['Superior reasoning skills', 'Industry-leading context window (200K)', 'Fewer refusals and higher accuracy'],
    cons: ['Higher cost per token', 'Slightly slower than smaller models'],
    bestFor: 'Legal document analysis, financial modeling, and research paper reviews.',
    quickstart: ['Sign up for the Claude API.', 'Choose the `claude-3-opus-20240229` model.', 'Structure your prompt for complex analysis.'],
    categories: ['Language Models'],
    tags: ['Anthropic', 'Reasoning', 'Long Context', 'Enterprise'],
  },
  {
    id: '3',
    slug: 'midjourney',
    name: 'Midjourney',
    summary: 'A premier AI image generator known for its artistic and highly detailed outputs.',
    websiteUrl: 'https://www.midjourney.com/',
    logoUrl: 'https://picsum.photos/seed/midjourney/100',
    pricingModel: 'Paid',
    freeTier: false,
    rating: 4.7,
    verdict: 'Unmatched for creating artistic, stylistic, and professional-grade imagery. The go-to for designers and artists.',
    pros: ['Incredible artistic quality', 'Coherent and detailed images', 'Active community and frequent updates'],
    cons: ['Interface is via Discord', 'Steep learning curve for advanced prompting'],
    bestFor: 'Concept art, illustrations, and photorealistic marketing visuals.',
    quickstart: ['Join the Midjourney Discord server.', 'Use the `/imagine` command in a newbie channel.', 'Experiment with style and aspect ratio parameters.'],
    categories: ['Image Generation'],
    tags: ['Art', 'Design', 'Creative', 'Discord'],
    youtubeReviewId: 'O5nsc3f30bU',
  },
  {
    id: '4',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    summary: 'Realistic and versatile text-to-speech (TTS) and voice cloning AI.',
    websiteUrl: 'https://elevenlabs.io/',
    logoUrl: 'https://picsum.photos/seed/elevenlabs/100',
    pricingModel: 'Freemium',
    freeTier: true,
    rating: 4.8,
    verdict: 'The industry standard for lifelike AI voices. Perfect for narration, podcasts, and character voices.',
    pros: ['Extremely realistic voices', 'Low-latency API', 'Instant voice cloning capabilities'],
    cons: ['Free tier is limited', 'Cloning requires clear audio samples'],
    bestFor: 'YouTube narration, audiobooks, and accessibility tools.',
    quickstart: ['Sign up and get a free API key.', 'Use the Speech Synthesis endpoint to convert text.', 'For cloning, upload a 1-minute audio sample without background noise.'],
    categories: ['Audio', 'Text-to-Speech'],
    tags: ['Voice', 'TTS', 'API', 'Audiobook'],
  },
  {
    id: '5',
    slug: 'routellm',
    name: 'RouteLLM',
    summary: 'A unified API gateway to access and benchmark hundreds of LLMs from various providers.',
    websiteUrl: 'https://abacus.ai/app/route-llm-apis',
    logoUrl: 'https://picsum.photos/seed/routellm/100',
    pricingModel: 'Usage-based',
    freeTier: true,
    rating: 4.6,
    verdict: 'An essential developer tool for abstracting away AI provider complexity and optimizing for cost and performance.',
    pros: ['Single API for many models', 'Automatic fallbacks and retries', 'Cost and latency optimization'],
    cons: ['Adds a small layer of latency', 'Model availability depends on upstream providers'],
    bestFor: 'Developers building AI-powered applications who need flexibility.',
    quickstart: ['Sign up and get a RouteLLM API key.', 'Replace your provider-specific SDK with a simple HTTP request.', 'Specify the model you want in the request body.'],
    categories: ['Developer Tools', 'API'],
    tags: ['LLM', 'Gateway', 'DevTool', 'Optimization'],
  },
  {
    id: '6',
    slug: 'make-com',
    name: 'Make.com',
    summary: 'A powerful no-code automation platform to connect apps and services.',
    websiteUrl: 'https://www.make.com/',
    logoUrl: 'https://picsum.photos/seed/make/100',
    pricingModel: 'Freemium',
    freeTier: true,
    rating: 4.7,
    verdict: 'The best visual automation builder for complex, multi-step workflows without writing any code.',
    pros: ['Intuitive visual interface', 'Extensive library of app integrations', 'Powerful logic and error handling features'],
    cons: ['Can get expensive with high operation counts', 'Some advanced features require learning'],
    bestFor: 'Automating business processes, marketing funnels, and content pipelines.',
    quickstart: ['Sign up for a free account.', 'Create a new scenario and add your first module (e.g., a webhook).', 'Connect modules by dragging and dropping.'],
    categories: ['Automation', 'No-Code'],
    tags: ['Workflow', 'Integration', 'Productivity'],
    youtubeReviewId: 'L8gV83G2b4o'
  },
];

export const UTILITY_CATEGORIES = [
  {
    id: 'cat-seo',
    name: 'SEO',
    slug: 'seo',
    description: 'Tools to optimize discoverability, thumbnails, titles, and metadata for better reach and engagement.',
    icon: 'SearchIcon',
    subcategories: [
      {
        id: 'sub-video-seo',
        name: 'Video SEO',
        slug: 'video-seo',
        description: 'Summarization, chapters, and metadata extraction for videos.',
        icon: 'VideoCameraIcon',
      },
      {
        id: 'sub-thumbnails',
        name: 'Thumbnails',
        slug: 'thumbnails',
        description: 'Prompt generation and testing tools to craft click-worthy thumbnails.',
        icon: 'CameraIcon',
      },
      {
        id: 'sub-titles-hooks',
        name: 'Titles & Hooks',
        slug: 'titles-hooks',
        description: 'Generate attention-grabbing titles and hooks for your audience.',
        icon: 'TitleIcon',
      },
    ],
  },
  {
    id: 'cat-content-management',
    name: 'Content Management',
    slug: 'content-management',
    description: 'Tools for transcribing, formatting, repurposing, and editing content across formats.',
    icon: 'FolderIcon',
    subcategories: [
      {
        id: 'sub-captions',
        name: 'Captions & Subtitles',
        slug: 'captions',
        description: 'Formatting and styling tools for captions and subtitles.',
        icon: 'ClosedCaptionIcon',
      },
      {
        id: 'sub-transcription',
        name: 'Transcription',
        slug: 'transcription',
        description: 'Audio and video transcription with timestamps and speaker detection.',
        icon: 'MicrophoneIcon',
      },
      {
        id: 'sub-repurpose',
        name: 'Repurposing',
        slug: 'repurposing',
        description: 'Turn long-form content into social posts, summaries, and key takeaways.',
        icon: 'SparklesIcon',
      },
      {
        id: 'sub-images',
        name: 'Image Editing',
        slug: 'image-editing',
        description: 'Edit and refine images using AI-powered tools.',
        icon: 'WandIcon',
      },
      {
        id: 'sub-thumbnail-creation',
        name: 'Thumbnail Creation',
        slug: 'thumbnail-creation',
        description: 'Generate thumbnails from prompts and templates.',
        icon: 'ImageIcon',
      },
    ],
  },
  {
    id: 'cat-saas',
    name: 'SaaS / Productivity',
    slug: 'saas',
    description: 'Productivity and SaaS-style tools to help creators move faster and produce better work.',
    icon: 'Cog6ToothIcon',
    subcategories: [
      {
        id: 'sub-video-tools',
        name: 'Video Tools',
        slug: 'video-tools',
        description: 'Short-form generation and clip creation tools.',
        icon: 'FilmIcon',
      },
      {
        id: 'sub-productivity',
        name: 'Productivity',
        slug: 'productivity',
        description: 'Coaching, presentation, and workflow-driven productivity tools.',
        icon: 'LightningBoltIcon',
      },
    ],
  },
];

export const UTILITIES_DATA: Utility[] = [
  {
    id: '1',
    slug: 'titles-hooks-generator',
    name: 'Titles/Hooks Generator',
    description: 'Generate 10 compelling titles and hooks for your topic and audience.',
    path: '/utilities/titles-hooks-generator',
    icon: 'TitleIcon',
    category: 'seo',
    subcategory: 'titles-hooks',
    badge: 'POPULAR',
    estimatedTime: '1-2 min',
    difficulty: 'Easy',
    steps: ['Enter your topic', 'Describe your audience', 'Get 10 title variations'],
    useCases: ['YouTube videos', 'Blog posts', 'Email subjects'],
  },
  {
    id: '2',
    slug: 'youtube-chapters-summary',
    name: 'YouTube → Chapters/Summary',
    description: 'Extract chapters with timestamps and a concise summary from any YouTube video.',
    path: '/utilities/youtube-chapters-summary',
    icon: 'ListIcon',
    category: 'seo',
    subcategory: 'video-seo',
    badge: 'POPULAR',
    estimatedTime: '2-3 min',
    difficulty: 'Easy',
    steps: ['Paste YouTube URL', 'AI extracts chapters', 'Get summary & timestamps'],
    useCases: ['Video optimization', 'Study notes', 'Content research'],
  },
  {
    id: '3',
    slug: 'captions-formatter',
    name: 'Captions/Subtitle Formatter',
    description: 'Clean up raw text or format it into a perfect SRT file with style notes.',
    path: '/utilities/captions-formatter',
    icon: 'ClosedCaptionIcon',
    category: 'content-management',
    subcategory: 'captions',
    estimatedTime: '1-2 min',
    difficulty: 'Easy',
    steps: ['Paste raw captions', 'Choose SRT format', 'Download formatted file'],
    useCases: ['Video subtitles', 'Accessibility', 'YouTube captions'],
  },
  {
    id: '4',
    slug: 'thumbnail-prompt-generator',
    name: 'Thumbnail Prompt Generator',
    description: 'Get creative thumbnail ideas with color and font cues for your video topic.',
    path: '/utilities/thumbnail-prompt-generator',
    icon: 'ImageIcon',
    category: 'seo',
    subcategory: 'thumbnails',
    badge: 'POPULAR',
    estimatedTime: '1 min',
    difficulty: 'Easy',
    steps: ['Describe video topic', 'Get AI thumbnail prompts', 'Use in design tools'],
    useCases: ['Midjourney prompts', 'Thumbnail design', 'Visual ideas'],
  },
  {
    id: '10',
    slug: 'thumbnail-generator',
    name: 'AI Thumbnail Generator',
    description: 'Generate high-quality, click-worthy thumbnails from a text prompt. (Pro Feature)',
    path: '/utilities/thumbnail-generator',
    icon: 'SparklesIcon',
    category: 'content-management',
    subcategory: 'thumbnail-creation',
    badge: 'PRO',
    estimatedTime: '2-3 min',
    difficulty: 'Easy',
    steps: ['Enter text prompt', 'AI generates thumbnail', 'Download & use'],
    useCases: ['Quick thumbnails', 'A/B testing', 'Concept validation'],
  },
  {
    id: '5',
    slug: 'thumbnail-tester',
    name: 'Interactive Thumbnail Tester',
    description: 'Get AI-driven feedback on your thumbnail\'s effectiveness for attracting clicks.',
    path: '/utilities/thumbnail-tester',
    icon: 'CameraIcon',
    category: 'seo',
    subcategory: 'thumbnails',
    badge: 'POPULAR',
    estimatedTime: '1-2 min',
    difficulty: 'Easy',
    steps: ['Upload thumbnail', 'AI analyzes design', 'Get score & feedback'],
    useCases: ['CTR optimization', 'A/B testing', 'Design validation'],
  },
  {
    id: '9',
    slug: 'ai-image-editor',
    name: 'AI Image Editor',
    description: 'Upload an image and use text prompts to edit it with AI. (Pro Feature)',
    path: '/utilities/ai-image-editor',
    icon: 'WandIcon',
    category: 'content-management',
    subcategory: 'image-editing',
    badge: 'PRO',
    estimatedTime: '2-4 min',
    difficulty: 'Medium',
    steps: ['Upload image', 'Describe changes', 'AI edits image'],
    useCases: ['Quick edits', 'Background removal', 'Style changes'],
  },
  {
    id: '11',
    slug: 'presentation-coach',
    name: 'Live Presentation Coach',
    description: 'Practice your speech with real-time transcription and get instant AI feedback. (Pro Feature)',
    path: '/utilities/presentation-coach',
    icon: 'MicrophoneIcon',
    category: 'saas',
    subcategory: 'productivity',
    badge: 'PRO',
    estimatedTime: '5-10 min',
    difficulty: 'Medium',
    steps: ['Start recording', 'Practice speech', 'Get AI feedback'],
    useCases: ['Speech practice', 'Presentation prep', 'Public speaking'],
  },
  {
    id: '6',
    slug: 'video-clip-generator',
    name: 'Video Clip Generator',
    description: 'Create a short video from a text prompt and an optional image using Veo.',
    path: '/utilities/video-clip-generator',
    icon: 'FilmIcon',
    category: 'saas',
    subcategory: 'video-tools',
    badge: 'BETA',
    estimatedTime: '3-5 min',
    difficulty: 'Medium',
    steps: ['Enter text prompt', 'Upload image (optional)', 'AI generates video'],
    useCases: ['Social media clips', 'Marketing videos', 'Content creation'],
  },
  {
    id: '7',
    slug: 'video-audio-transcriber',
    name: 'Video/Audio Transcriber',
    description: 'Upload a video or audio file to generate an accurate, timestamped transcript.',
    path: '/utilities/video-audio-transcriber',
    icon: 'MicrophoneIcon',
    category: 'content-management',
    subcategory: 'transcription',
    badge: 'POPULAR',
    estimatedTime: '2-5 min',
    difficulty: 'Easy',
    steps: ['Upload file', 'AI transcribes', 'Get timestamped text'],
    useCases: ['Podcast transcripts', 'Meeting notes', 'Video captions'],
  },
  {
    id: '8',
    slug: 'content-repurposer',
    name: 'Content Repurposer',
    description: 'Turn a long transcript or text into a summary, key takeaways, and social media posts.',
    path: '/utilities/content-repurposer',
    icon: 'SparklesIcon',
    category: 'content-management',
    subcategory: 'repurposing',
    badge: 'POPULAR',
    estimatedTime: '2-3 min',
    difficulty: 'Easy',
    steps: ['Paste content', 'Choose formats', 'Get repurposed content'],
    useCases: ['Social posts', 'Newsletters', 'Twitter threads'],
  },
  {
    id: '12',
    slug: 'ai-resume-builder',
    name: 'AI Resume Builder',
    description: 'Paste a job description to get tailored resume optimization, key skills, and improvement tips.',
    path: '/utilities/ai-resume-builder',
    icon: 'DocumentIcon',
    category: 'saas',
    subcategory: 'productivity',
    badge: 'NEW',
    estimatedTime: '3-4 min',
    difficulty: 'Easy',
    steps: ['Paste job description', 'Add resume (optional)', 'Get tailored resume'],
    useCases: ['Job applications', 'Resume optimization', 'Career coaching'],
  },
  {
    id: '13',
    slug: 'voice-to-blog',
    name: 'Voice-to-Blog Generator',
    description: 'Record your voice or paste a transcript and transform it into a professional blog post.',
    path: '/utilities/voice-to-blog',
    icon: 'MicrophoneIcon',
    category: 'content-management',
    subcategory: 'repurposing',
    badge: 'NEW',
    estimatedTime: '3-5 min',
    difficulty: 'Medium',
    steps: ['Record voice OR paste text', 'AI processes', 'Get full blog post'],
    useCases: ['Podcasts to blogs', 'Voice notes', 'Quick content'],
  },
  {
    id: '14',
    slug: 'csv-data-visualizer',
    name: 'CSV Data Visualizer',
    description: 'Upload CSV data to get AI-powered insights, trend analysis, and visualization recommendations.',
    path: '/utilities/csv-data-visualizer',
    icon: 'ChartIcon',
    category: 'saas',
    subcategory: 'productivity',
    badge: 'NEW',
    estimatedTime: '2-4 min',
    difficulty: 'Medium',
    steps: ['Upload CSV OR paste data', 'AI analyzes', 'Get insights & charts'],
    useCases: ['Data analysis', 'Business reports', 'Trend discovery'],
  },
  {
    id: '15',
    slug: 'linkedin-post-optimizer',
    name: 'LinkedIn Post Optimizer',
    description: 'Optimize your LinkedIn posts for maximum engagement with AI-powered suggestions.',
    path: '/utilities/linkedin-post-optimizer',
    icon: 'SparklesIcon',
    category: 'content-management',
    subcategory: 'repurposing',
    badge: 'NEW',
    estimatedTime: '2-3 min',
    difficulty: 'Easy',
    steps: ['Paste LinkedIn post', 'Choose goal', 'Get optimized version'],
    useCases: ['LinkedIn marketing', 'Engagement', 'Thought leadership'],
  },
  {
    id: '16',
    slug: 'code-debugger',
    name: 'Code Debugger',
    description: 'Paste your buggy code and get AI explanations, fixes, and prevention tips.',
    path: '/utilities/code-debugger',
    icon: 'CodeIcon',
    category: 'saas',
    subcategory: 'productivity',
    badge: 'NEW',
    estimatedTime: '2-3 min',
    difficulty: 'Easy',
    steps: ['Paste code', 'Add error message', 'Get fix & explanation'],
    useCases: ['Bug fixing', 'Learning code', 'Code review'],
  },
  {
    id: '17',
    slug: 'email-response-generator',
    name: 'Email Response Generator',
    description: 'Paste any email and get a professional response draft in your chosen tone within seconds.',
    path: '/utilities/email-response-generator',
    icon: 'SparklesIcon',
    category: 'saas',
    subcategory: 'productivity',
    badge: 'NEW',
    estimatedTime: '1-2 min',
    difficulty: 'Easy',
    steps: ['Paste received email', 'Choose tone', 'Get response draft'],
    useCases: ['Business emails', 'Customer support', 'Quick replies'],
  },
  {
    id: '18',
    slug: 'meeting-minutes-generator',
    name: 'Meeting Minutes Generator',
    description: 'Turn meeting transcripts into structured minutes with action items, decisions, and key points.',
    path: '/utilities/meeting-minutes-generator',
    icon: 'MicrophoneIcon',
    category: 'content-management',
    subcategory: 'transcription',
    badge: 'NEW',
    estimatedTime: '3-5 min',
    difficulty: 'Medium',
    steps: ['Paste transcript', 'AI analyzes meeting', 'Get formatted minutes'],
    useCases: ['Team meetings', 'Client calls', 'Documentation'],
  },
  {
    id: '19',
    slug: 'business-name-generator',
    name: 'Business Name Generator',
    description: 'Get 15 creative, brandable business names with taglines and domain suggestions for your startup.',
    path: '/utilities/business-name-generator',
    icon: 'SparklesIcon',
    category: 'saas',
    subcategory: 'productivity',
    badge: 'NEW',
    estimatedTime: '2 min',
    difficulty: 'Easy',
    steps: ['Describe business', 'Add keywords', 'Get 15 name ideas'],
    useCases: ['Startups', 'Rebranding', 'Side projects'],
  },
];

export const WORKFLOWS_DATA: Workflow[] = [
  {
    id: '1',
    slug: 'youtube-to-blog',
    name: 'YouTube Video to Blog Post',
    description: 'Automatically transcribe a YouTube video, generate a summary with Gemini, and create a draft blog post in Google Docs.',
    services: ['YouTube', 'Gemini', 'Google Docs', 'Make'],
    icon: 'RocketLaunchIcon',
    deploymentUrl: 'https://www.make.com/en/templates/1943-create-a-blog-post-from-a-youtube-video-using-gemini',
  },
  {
    id: '2',
    slug: 'newsletter-automation',
    name: 'AI-Powered Newsletter',
    description: 'Summarize a list of articles using Gemini, format it into a newsletter template, and send it via Mailchimp.',
    services: ['RSS', 'Gemini', 'Mailchimp', 'Zapier'],
    icon: 'RocketLaunchIcon',
    deploymentUrl: 'https://zapier.com/apps/gemini/integrations',
  },
  {
    id: '3',
    slug: 'social-media-content-pipeline',
    name: 'Social Media Content Pipeline',
    description: 'Take a long-form article, generate 5 unique social media posts with Gemini, and schedule them to be posted on Twitter.',
    services: ['Web Page', 'Gemini', 'Buffer', 'Make'],
    icon: 'RocketLaunchIcon',
    deploymentUrl: 'https://www.make.com/en/templates/1943-create-a-blog-post-from-a-youtube-video-using-gemini',
  },
   {
    id: '4',
    slug: 'customer-support-tagging',
    name: 'Automated Support Ticket Tagging',
    description: 'When a new support ticket arrives in Zendesk, use Gemini to analyze the content and automatically apply relevant tags.',
    services: ['Zendesk', 'Gemini', 'Zapier'],
    icon: 'RocketLaunchIcon',
    deploymentUrl: 'https://zapier.com/apps/gemini/integrations/zendesk',
  }
];

export const FORUM_CATEGORIES = [
  {
    id: 'forum-general',
    name: 'General Discussion',
    slug: 'general-discussion',
    description: 'General chat about AI tools, workflows, and creator strategies.',
    icon: 'ChatBubbleIcon',
  },
  {
    id: 'forum-reviews',
    name: 'Tool Reviews',
    slug: 'tool-reviews',
    description: 'Share and read reviews of AI tools and services.',
    icon: 'StarIcon',
  },
  {
    id: 'forum-workflows',
    name: 'Workflow Sharing',
    slug: 'workflow-sharing',
    description: 'Post your automation and workflow recipes, templates, and integrations.',
    icon: 'BeakerIcon',
  },
  {
    id: 'forum-requests',
    name: 'Feature Requests',
    slug: 'feature-requests',
    description: 'Request new features, improvements, or tools you want in the platform.',
    icon: 'LightBulbIcon',
  },
  {
    id: 'forum-support',
    name: 'Help & Support',
    slug: 'help-and-support',
    description: 'Get help with tools, account issues, or how to use a feature.',
    icon: 'SupportIcon',
  },
  {
    id: 'forum-showcase',
    name: 'Showcase',
    slug: 'showcase',
    description: 'Show off your projects, videos, and work created using the platform.',
    icon: 'PhotographIcon',
  },
];

export const NEWS_CATEGORIES = [
  {
    id: 'news-ai-tools',
    name: 'AI Tools',
    slug: 'ai-tools',
    description: 'Announcements and reviews of new AI tools and product launches.',
    icon: 'PuzzlePieceIcon',
  },
  {
    id: 'news-industry',
    name: 'Industry News',
    slug: 'industry-news',
    description: 'Broader industry updates, company moves, acquisitions, and trends.',
    icon: 'GlobeAltIcon',
  },
  {
    id: 'news-tutorials',
    name: 'Tutorials',
    slug: 'tutorials',
    description: 'How-tos, deep dives, and practical guides for using AI tools effectively.',
    icon: 'AcademicCapIcon',
  },
  {
    id: 'news-updates',
    name: 'Product Updates',
    slug: 'product-updates',
    description: 'Changelogs, release notes, and official product updates.',
    icon: 'SparklesIcon',
  },
  {
    id: 'news-research',
    name: 'Research',
    slug: 'research',
    description: 'Papers, benchmarks, and research breakthroughs in AI and ML.',
    icon: 'BeakerIcon',
  },
];